### ISSUE TITLE
In line code and line breaks

### ISSUE THREAD

**Issue by Ynzl** [psibi/tldr-hs#11]
I'm not sure if this is an issue here or should be in the main repo. So if this issue doesn't belong here, please point me to the correct place.

There is a problem with "inline" code snippets. Each snippet is put into a single line.

E.g. for `grep` in
```
- Use extended regular expressions (supporting `?`, `+`, `{}`, `()` and `|`):
```
Each of `?`, `+`, `{}`, `()` and `|` is put in its own line.

I'm on Ubuntu 18.04.1 with `tldr/bionic,now 0.2.3-3 amd64`

**Comment by psibi** [comment]
@Ynzl Thanks for the bug report, I can reproduce this. I will get to this in the coming weekend.

**Comment by psibi** [comment]
@Ynzl I have release `tldr-0.3.1` which fixes the bug. I have also added test cases so that regression doesn't happen in future. Thanks for the bug report.

**Comment by psibi** [comment]
Upstream usually takes quite a bit of time to catch up.

The quickest way would be compile this locally now or wait for a couple of days till stackage nightly get's the latest one: https://github.com/commercialhaskell/stackage/pull/3989

Let me know if you need any help in any of the activities.
