### ISSUE TITLE
broken display with asterisc in grave accent

### ISSUE THREAD

**Issue by conao3** [psibi/tldr-hs#18]
Hi! Original issue is [here](https://github.com/tldr-pages/tldr/pull/3447)
> I found broken display at git-branch page.
It seems that the asterisk is surrounded by code blocks, but it is not well recognized and misunderstood as a chapter break.
Converted to single quotes, but more fundamental changes may be required

![](https://user-images.githubusercontent.com/4703128/67139276-485ce680-f289-11e9-880d-adc9195289c9.png)

I use `tldr` in Ubuntu-bionic and installed it with `apt install tldr`.

[Additional research](https://github.com/tldr-pages/tldr/pull/3447#issuecomment-544360522) revealed that I am using the Haskell version of `tldr` in the terminal.
I would like to report an issue.

---
P.S.
I have not ever used Haskell and `stack` is not installed.
I just installed it with `sudo apt install tldr`, but it seems that Haskell version of `tldr` was installed. Is this behavior intended?
```
conao-macbook:~ conao
$ which stack

conao-macbook:~ conao
$ stack

Command 'stack' not found, but can be installed with:

sudo apt install haskell-stack
```

**Comment by psibi** [comment]
@conao3 I think Ubuntu ships with an older version of `tldr`. I remember fixing the issue:

![tldr-snap](https://user-images.githubusercontent.com/737477/67183120-584a0700-f3fe-11e9-8543-3bdaef68f047.png)

Can you instead try installing from source ? These are the steps:

* Clone repo: `git clone https://github.com/psibi/tldr-hs.git`
* Install stack: https://docs.haskellstack.org/en/stable/README/#how-to-install
* `cd tldr-hs`
* `stack setup`
* `stack build`
* `stack install`

Then you might need need to adjust the $PATH to have your `~/.local/bin` (or instead pass the option --local-bin-path to the above `stack install` command. Let me know if you need any help. Thanks!

**Comment by conao3** [comment]
OK, I will. Thanks!
(my `tldr --version` outputs `0.2.3` this is so old! :) Sorry this noise.)
