### ISSUE TITLE
More verbose version

### ISSUE THREAD

**Issue by stites** [psibi/tldr-hs#19]
very low priority, but it would be nice to have a slightly more verbose version output. For example, the official tldr client outputs the following:
 
```
❯ ~/.nix-profile/bin/tldr -v
/home/stites/.nix-profile/bin/tldr v1.3.0
Copyright (C) 2016 Arvid Gerstmann
Source available at https://github.com/tldr-pages/tldr-cpp-client
```

**Comment by psibi** [comment]
@stites Thanks for the feedback! If you are interested, you can send a PR for the same. Or else I will see if I can get this fixed this weekend (or by the end of this month).

**Comment by psibi** [comment]
@stites I looked into this today and it seems the CPP client has two different options:
* -v for verbose
* --version for version

Given that in Unix, the general convention is that `-v` and --version` both mean the same thing I'm not sure if it would be a good idea to treat `-v` and `--version` different. What do you think about adding a separate option named `--about` ?

**Comment by psibi** [comment]
@stites I have implemented a sample version in https://github.com/psibi/tldr-hs/pull/20:

```
$ tldr --about
/home/sibi/.local/bin/tldr v0.6.0
Copyright (C) 2017 Sibi Prabakaran
Source available at https://github.com/psibi/tldr-hs
```

What do you think ?

**Comment by stites** [comment]
That's great, thanks!

**Comment by psibi** [comment]
A new version `0.6.1` has been uploaded to Hackage which contains this changes. Thanks!
