### ISSUE TITLE
Client returns 0 for nonexistent commands

### ISSUE THREAD

**Issue by samuel-w** [psibi/tldr-hs#24]
Run the following:
```
tldr foo; echo $?
```
0 will be printed out, despite foo not having a tldr entry. Discovered by letompouce tldr-pages/tldr#4227

**Comment by psibi** [comment]
It seems the original issue seems to be using a different client based on the error message. The haskell one will fall back to the english locale if it doesn't find page based on the existing locale. Eg:

```
$ ~/g/tldr-hs (exit-code) $ tldr -L ja ss
ss
Utility to investigate sockets.

 - Show all TCP/UDP/RAW/UNIX sockets:
```

But again this client shows a wrong exit code if the page isn't found. I will fix it. Thanks for the report.

**Comment by psibi** [comment]
A new version v0.7.1 has been released which contains the fix.
