### ISSUE TITLE
Multiple lines rendered as one

### ISSUE THREAD

**Issue by samuel-w** [psibi/tldr-hs#26]
In tldr-hs, multiple description lines are rendered as one. For example, `tldr tar`

> tar
> Archiving utility.Often combined with a compression method, such as gzip or bzip.More information: https://www.gnu.org/software/tar.

In tldr-python-client and tldr-node-client

>   tar
> 
>   Archiving utility.
>   Often combined with a compression method, such as gzip or bzip.
>   More information: https://www.gnu.org/software/tar.

**Comment by psibi** [comment]
@samuel-w Thanks for the report! I didn't notice this until this issue. I will fix this by the coming weekend.

**Comment by psibi** [comment]
@samuel-w This has been fixed and a new release v0.8.0 has been made which contains the fix. Thanks for the report!
