### ISSUE TITLE
tldr output formatting not compatible with tldr python or rust clients

### ISSUE THREAD

**Issue by fazlearefin** [psibi/tldr-hs#44]
This Haskell client of tldr displays tldr pages differently to the official python and rust clients. 

This Haskell implementation of tldr shows `tldr cat` like this (I am using 0.6.4 bundled with Ubuntu 22.04):

```
cat
Print and concatenate files.More information: https://www.gnu.org/software/coreutils/cat.

 - Print the contents of a file to the standard output:
   cat {{file}}

 - Concatenate several files into the target file:
   cat {{file1}} {{file2}} > {{target_file}}

 - Append several files into the target file:
   cat {{file1}} {{file2}} >> {{target_file}}

 - Number all output lines:
   cat -n {{file}}

 - Display non-printable and whitespace characters (with M- prefix if non-ASCII):
   cat -v -t -e {{file}}
```

However, both the python and rust implementations of tldr displays like this:

```
cat

  Print and concatenate files.
  More information: https://www.gnu.org/software/coreutils/cat.

  - Print the contents of a file to the standard output:
    cat file

  - Concatenate several files into the target file:
    cat file1 file2 > target_file

  - Append several files into the target file:
    cat file1 file2 >> target_file

  - Number all output lines:
    cat -n file

  - Display non-printable and whitespace characters (with `M-` prefix if non-ASCII):
    cat -v -t -e file
```

So this Haskell implementation:
- does not honor newlines at the top of the page showing the description of the command in general
- shows the `{{` and `}}` chars whereas the python and rust implementations shows them in color or underlined (not possible to show here using markdown)

**Comment by psibi** [comment]
This is how it display in version 0.9.1:

![tldr_cat](https://user-images.githubusercontent.com/737477/169706113-5554cf3b-471b-469d-a256-427379414f93.png)

**Comment by fazlearefin** [comment]
Looks good then. Too bad Ubuntu 22.04 is still stuck with `0.6.4`
